<?php
namespace App\Form;
use App\Entity\Category;
use App\Filtrer\Filter;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Doctrine\Common\Collections\ArrayCollection;

class SearchType extends AbstractType{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('string', TextType::class, [
                'label'=> false,
                'required' =>false,
                'attr'=>[
                    'placeholder'=> 'Votre recherche...',
                    'class'=>'form_control-sm'

                ]

        ])
        ->add('categories', EntityType::class, [

           'class'=>Category::class,
            'required'=> false,
            'multiple'=>true,
            'expanded'=>true



        ])->add("submit", SubmitType::class, [
                "label" => "Filtrer",
                "attr" => [
                    "class" => "btn-block btn-info"
                ]
            ])
        ;

    }
       public function configureOptions(OptionsResolver $resolver)
       {
           $resolver->setDefaults([
               'data_class' => Filter::class,
               'method'=> 'GET',
               'crsf_protection'=> false,

           ])
               ;
       }

    public function getBlockPrefix()
    {
        return '';
            //parent::getBlockPrefix(); // TODO: Change the autogenerated stub
    }

}